steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.app
      - -t
      - europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-app:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-app:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cookie-jar-app-e2
      - --image=europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-app:$COMMIT_SHA
      - --region=europe-west1
      - --platform=managed
      - --concurrency=8
      - --max-instances=4
      - --set-env-vars=FLASK_DEBUG=0
      # Optional: add --service-account, --set-cloudsql-instances, --vpc-connector in step 2

options:
  logging: CLOUD_LOGGING_ONLY
