steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - tools/locust/Dockerfile
      - -t
      - europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-locust:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-locust:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - cookie-jar-locust-e2
      - --image=europe-west1-docker.pkg.dev/dept-dinl-angela/cookie-jar/cookie-jar-locust:$COMMIT_SHA
      - --region=europe-west1
      - --service-account=angela-masters@dept-dinl-angela.iam.gserviceaccount.com
      - --tasks=1
      - --max-retries=0
      - --task-timeout=3600s
      - --command=python3
      - --args=tools/locust/run_locust_benchmarks.py
      - --set-env-vars=PYTHONUNBUFFERED=1

options:
  logging: CLOUD_LOGGING_ONLY
