"""removing translations tables

Revision ID: 9211556ac2d8
Revises: d6513f12a115
Create Date: 2026-05-10 15:57:03.932914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9211556ac2d8'
down_revision = 'd6513f12a115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_purpose_translation')
    op.drop_table('vendor_description_translation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_description_translation',
    sa.Column('vendor_description_translation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_description_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_iso_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_description_translation', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_iso_code_id'], ['language_iso_code.language_iso_code_id'], name='vendor_description_translation_language_iso_code_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_description_id'], ['vendor_description.vendor_description_id'], name='vendor_description_translation_vendor_description_id_fkey'),
    sa.PrimaryKeyConstraint('vendor_description_translation_id', name='vendor_description_translation_pkey')
    )
    op.create_table('tracker_purpose_translation',
    sa.Column('tracker_purpose_translation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracker_purpose_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_iso_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracker_purpose_translation', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_iso_code_id'], ['language_iso_code.language_iso_code_id'], name='tracker_purpose_translation_language_iso_code_id_fkey'),
    sa.ForeignKeyConstraint(['tracker_purpose_id'], ['tracker_purpose.tracker_purpose_id'], name='tracker_purpose_translation_tracker_purpose_id_fkey'),
    sa.PrimaryKeyConstraint('tracker_purpose_translation_id', name='tracker_purpose_translation_pkey')
    )
    # ### end Alembic commands ###
